#!/usr/bin/python

import argparse
import Inelastica.MakeGeom as MG
import Inelastica.info as info

description = """
Tool for converting geometries between different files.
Currently supports XV, xyz, fdf, ANI, and mkl.
Repeat unitcell from XV and fdf.
(fdf support limited to Ang, cartesian coord)
"""

parser = argparse.ArgumentParser(description=description)
parser.add_argument('GIN', help='Input geometry file')
parser.add_argument('GOUT', help='Output geometry file')
parser.add_argument('-x', '--A1', type=int, default=1,
                    help='Repeat unitcell along lattice vector A1')
parser.add_argument('-y', '--A2', type=int, default=1,
                    help='Repeat unitcell along lattice vector A2')
parser.add_argument('-z', '--A3', type=int, default=1,
                    help='Repeat unitcell along lattice vector A3')
parser.add_argument('-v','--version', action='version', version='Inelastica %s' %info.version)
args = parser.parse_args()

rep = [args.A1, args.A2, args.A3]
print 'Converting %s to %s with repetition'%(args.GIN, args.GOUT), rep
MG.convert(args.GIN, args.GOUT, rep=rep)
