#!/usr/bin/env python

import sys
from datetime import datetime

import Inelastica.iets as Module
import Inelastica.io.log as Log

start = datetime.now()

options = Module.GetOptions(sys.argv[1:])
Module.main(options)

dT = datetime.now()-start

Log.PrintScriptSummary(sys.argv, dT)
