#!/usr/bin/env python

import sys
from datetime import datetime

import Inelastica.iets as Module
import Inelastica.CommonFunctions as CF

start = datetime.now()

options = Module.GetOptions(sys.argv[1:])
Module.main(options)

dT = datetime.now()-start

CF.PrintScriptSummary(sys.argv, dT)
