#!/usr/bin/env python

import Inelastica.SetupRuns as SR
import argparse

parser = argparse.ArgumentParser(description='Tool for generating the OSrun folder starting from CGrun')
parser.add_argument('CGrun',metavar='CG',
                    help='Input CGrun (or TSrun) directory name')
parser.add_argument('OSrun',metavar='OS',
                    help='Output OSrun directory name (to be created)')
parser.add_argument('-d', '--displacement',dest='displacement',type=float,default=0.02,
                    help='Finite displacement amplitude (default: %(default)s Ang')
args = parser.parse_args()

SR.SetupOSrun(args.CGrun,args.OSrun,args.displacement)
