#!/usr/bin/env python

import Inelastica.MakeGeom as MG
from optparse import OptionParser

usage = "usage: %prog from to [options]"
description = """
Tool for converting geometries between different files.
Currently supports XV, xyz, fdf, ANI, and mkl.
Repeat unitcell from XV and fdf.
(fdf support limited to Ang, cartesian coord)
"""
parser = OptionParser(usage,description=description)
parser.add_option("-x", "--Nx", help="Repeat unitcell in x-direction", type='int', default=1)
parser.add_option("-y", "--Ny", help="Repeat unitcell in y-direction", type='int', default=1)
parser.add_option("-z", "--Nz", help="Repeat unitcell in z-direction", type='int', default=1)
(general, args) = parser.parse_args()

if len(args)<2:
    print description
    parser.error('You need to supply two filenames.')
else:
    rep = [general.Nx, general.Ny, general.Nz]
    print 'Converting %s to %s with repetition'%(args[0],args[1]),rep
    MG.convert(args[0],args[1],rep=rep)
