#!/usr/bin/env python

import Inelastica.MakeGeom as MG
from optparse import OptionParser

usage = "usage: %prog from to [options]"
description = """
Tool for converting geometries between different files.
Currently supports XV, xyz, fdf, ANI, and mkl.
Repeat unitcell from XV and fdf.
(fdf support limited to Ang, cartesian coord)
"""
parser = OptionParser(usage,description=description)
parser.add_option("-f", "--first", help="First atom in Z-matrix range", type='int', default=0)
parser.add_option("-l", "--last", help="Last atom in Z-matrix range", type='int', default=0)
(general, args) = parser.parse_args()

if len(args)<2:
    print description
    parser.error('You need to supply two filenames.')
else:
    g = MG.Geom(args[0])
    g.writeFDFZmat(args[1],general.first,general.last)

