#!/usr/bin/env python

import sys
from datetime import datetime

from Inelastica import Phonons as PH

start = datetime.now()

options = PH.GetOptions(sys.argv[1:])

# Write function call
print '\n' + ' '.join(sys.argv) + '\n'

PH.main(options)

# Timing
dT = datetime.now()-start
hours = dT.days/24.+(dT.seconds+dT.microseconds*1.e-6)/60.**2
minutes = hours*60.
seconds = minutes*60.
print 'Total walltime %.2f hrs = %.2f min = %.2f sec'%(hours,minutes,seconds)
