#!/usr/bin/env python

import Inelastica.SetupRuns as SR
from optparse import OptionParser

usage = "usage: %prog <CGrun> <OSrun> [options]"
description = """
Tool for generating the OSrun folder starting from CGrun
"""
parser = OptionParser(usage,description=description)
parser.add_option("-d", "--displacement",dest="displacement",help="Finite displacement amplitude", type='float', default=0.02)

(general, args) = parser.parse_args()

if len(args)<2:
    print description
    parser.error('You need to supply two directories.')
else:
    SR.SetupOSrun(args[0],args[1],general.displacement)
