#!/usr/bin/python

from Inelastica import VaspIO as VIO
from Inelastica import SiestaIO as SIO
from Inelastica import PhysicalConstants as PC
import sys

# File to read
fn = sys.argv[1]

label,scalefactor,vectors,specieslabels,speciesnumbers,xyz = VIO.ReadCONTCAR(fn)

anr = []
snr = []
sn = 1

for i in range(len(speciesnumbers)):
    element = specieslabels[i]
    an = PC.PeriodicTable[element]
    for j in range(speciesnumbers[i]):
        anr.append(an)
        snr.append(sn)
    sn += 1

print 'anr ='
print anr
print 'snr'
print snr

# Move atoms inside unit cell
dx = raw_input('Shift along x-axis [default=0.0] (Ang)? ')
dy = raw_input('Shift along y-axis [default=0.0] (Ang)? ')
dz = raw_input('Shift along z-axis [default=0.0] (Ang)? ')
if len(dx)>0: dx = float(dx)
else: dx = 0.0
if len(dy)>0: dy = float(dy)
else: dy = 0.0
if len(dz)>0: dz = float(dz)
else: dz = 0.0
for i in range(len(xyz)):
    xyz[i][0] += dx
    xyz[i][1] += dy
    xyz[i][2] += dz
    for j in range(3):
        if xyz[i][j]-vectors[j][j]>0: xyz[i][j] -= vectors[j][j]
        if xyz[i][j]<0: xyz[i][j] += vectors[j][j]
        
SIO.WriteXVFile(fn+'.XV',vectors,snr,anr,xyz)
SIO.WriteXYZFile(fn+'.xyz',anr,xyz)
